name: Tool Installer
description: Dynamically dispatch tool installers

inputs:
  tool:
    required: true
  version:
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Install Tool
      shell: bash
      run: |
        TOOL="${{ inputs.tool }}"
        VERSION="${{ inputs.version }}"
        
        echo "🔧 Installing $TOOL (version: ${VERSION:-latest})"

        # Define the base path for tool installers
        BASE_INSTALLER_PATH=".github/actions/tool-installer/tools"

        # Construct the path dynamically
        TOOL_INSTALLER_PATH="${BASE_INSTALLER_PATH}/${TOOL}/action.yml"

        # Check if the tool installer exists
        if [[ ! -f "$TOOL_INSTALLER_PATH" ]]; then
          echo "❌ Installer not found for tool: $TOOL"
          exit 1
        fi

        echo "✅ Found installer for $TOOL at $TOOL_INSTALLER_PATH"

        # Use the GitHub Action to run the tool installer directly
        # This is the key part, using the `uses` directive correctly within YAML
        echo "Running the installer for $TOOL..."
        uses: $TOOL_INSTALLER_PATH
