name: Tool Installer
description: Dispatches to specific tool installers dynamically
inputs:
  tool:
    description: Tool name to install (e.g. python, node, matlab)
    required: true
  version:
    description: Version of the tool (optional)
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Validate tool exists
      shell: bash
      run: |
        TOOL="${{ inputs.tool }}"
        INSTALLER_PATH=".github/actions/tool-installer/tools/$TOOL/action.yml"

        if [[ ! -f "$INSTALLER_PATH" ]]; then
          echo "::error::Installer for tool '$TOOL' not found at $INSTALLER_PATH"
          exit 1
        fi

    - name: Install Tool
      uses: ./.github/actions/tool-installer/tools/${{ inputs.tool }}
      with:
        version: ${{ inputs.version }}
