name: Tool Installer
description: Installs a tool based on input
inputs:
  tool:
    required: true
  version:
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install Python
      if: ${{ inputs.tool == 'python' }}
      uses: ../tool-installer/tools/python
      with:
        version: ${{ inputs.version }}

    - name: Install Node
      if: ${{ inputs.tool == 'node' }}
      uses: ../tool-installer/tools/node
      with:
        version: ${{ inputs.version }}

    - name: Install MATLAB
      if: ${{ inputs.tool == 'matlab' }}
      uses: ../tool-installer/tools/matlab
      with:
        version: ${{ inputs.version }}
