name: Tool Installer
description: Dynamically dispatch to tool installers
inputs:
  tool:
    required: true
  version:
    required: false

runs:
  using: "composite"
  steps:
    - name: Validate Tool Action Exists
      shell: bash
      run: |
        TOOL_PATH=".github/actions/tool-installer/tools/${{ inputs.tool }}/action.yml"
        if [[ ! -f "$TOOL_PATH" ]]; then
          echo "❌ Tool installer not found: $TOOL_PATH"
          exit 1
        fi
        echo "✅ Found installer for ${{ inputs.tool }}"

    - name: Run Tool Installer
      uses: ./.github/actions/tool-installer/tools/${{ inputs.tool }}
      with:
        version: ${{ inputs.version }}
